[syntalos_module]
type = "python"

name = "Pupil Labs Neon"
description = "Streams data from Pupil Labs Neon glasses."
icon = "neon.svg"

main = "module.py"
# will run the module in a dedicated venv with requirements.txt installed
use_venv = true

# By default development modules don't show up in Syntalos
# unless you activate the developer mode.
devel = false

# This will put it inside the "Device Support" group in the "Add Module" GUI
categories = ['device']
features = ['show-settings']
